name: On push main

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create-image.outputs.tag }}
    steps:
      - id: create-tag
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  go-zip-builder-and-deployer:
    name: Build and deploy go zip
    runs-on: ubuntu-latest
    needs:
      - image-tag
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-deploy-go
        with:
          tag: ${{ needs.image-tag.outputs.image-tag }}
          deploy: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket-name: content-generator
          lambda-name: content-generator