name: On pull request main

on:
  pull_request:
    branches:
      - main

jobs:
  go-lint-test:
    name: Lint and test go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint-test-go

  go-builder:
    name: Build go
    needs: go-lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-deploy-go

  # GitHub branch protection rules let us set on required status check before merging.
  # This is the only status check that needs to be check in the rules.
  # https://github.com/community/community/discussions/4324
  can-deploy:
    runs-on: ubuntu-latest
    needs:
      - go-lint-test
      - go-builder
    if: always()
    steps:
      - name: successful
        if: ${{ !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: failing
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
